table 'Measure Table 1'
	lineageTag: d538e278-9081-4da1-980f-c248a28dee98

	measure 'Total Number of Days' = DISTINCTCOUNT('Demand/Availability Record'[Order_Date_DD_MM_YYYY].[Date])
		formatString: 0
		lineageTag: 9e11bb76-3789-40e1-aeaf-11127a487ab5

	measure 'Total Demand' = SUM('Demand/Availability Record'[Demand])
		formatString: 0
		lineageTag: 137d59a9-e6d5-46e2-b705-c6cd3430c3a9

	measure 'Total Availability' = SUM('Demand/Availability Record'[Availability])
		formatString: 0
		lineageTag: 6aa7838d-952f-457e-92f5-61f890244e43

	measure 'Average Demand Per Day' = DIVIDE([Total Demand],[Total Number of Days])
		lineageTag: fd059fb8-4881-4024-b639-3b6e26fd2300

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Availability Per Day' = DIVIDE([Total Availability],[Total Number of Days])
		lineageTag: b01f66a5-1ea4-4db1-985b-175bd046322c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Supply Shortage' = ```
			[Total Demand]- [Total Availability] 
			```
		formatString: 0
		lineageTag: b649ae6c-df7a-48fd-b5d0-314a9f4599cf

	partition 'Measure Table 1' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

