table 'Demand/Availability Record'
	lineageTag: f9e99477-0a51-4610-9140-60004059f8f8

	column Order_Date_DD_MM_YYYY
		dataType: dateTime
		formatString: Long Date
		lineageTag: b5167072-7a98-40de-bd2f-cfdc29fc7693
		summarizeBy: none
		sourceColumn: Order_Date_DD_MM_YYYY

		variation Variation
			isDefault
			relationship: 65947548-1703-4daa-8833-dc952577320a
			defaultHierarchy: LocalDateTable_86b8ec8f-7cd2-49be-92ab-7810170676da.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Product_ID
		dataType: int64
		formatString: 0
		lineageTag: f5644ef7-8331-4c58-afa9-9a1e3154efd0
		summarizeBy: count
		sourceColumn: Product_ID

		annotation SummarizationSetBy = Automatic

	column Availability
		dataType: int64
		formatString: 0
		lineageTag: 132d05f2-feb8-4b31-a970-95eda38c4736
		summarizeBy: sum
		sourceColumn: Availability

		annotation SummarizationSetBy = Automatic

	column Demand
		dataType: int64
		formatString: 0
		lineageTag: 63e1d5fd-b894-4f4e-b1a2-f8249b8bf177
		summarizeBy: sum
		sourceColumn: Demand

		annotation SummarizationSetBy = Automatic

	column Product_Name
		dataType: string
		lineageTag: 70365d66-dd6c-4bb7-87bf-36b7f9d855b0
		summarizeBy: none
		sourceColumn: Product_Name

		annotation SummarizationSetBy = Automatic

	column Unit_Price
		dataType: double
		lineageTag: f8a70793-2e8a-4d7f-a5b5-bf2d6da2b09f
		summarizeBy: sum
		sourceColumn: Unit_Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Loss/Profit = 'Demand/Availability Record'[Availability]-'Demand/Availability Record'[Demand]
		formatString: 0
		lineageTag: 3fc0d8cd-ca0a-4c38-b680-a66a68d2216b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Demand/Availability Record' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost", "prod", [ReturnSingleDatabase=true, Query="SELECT * FROM new_table;"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Order_Date_DD_MM_YYYY", type date}, {"Product_ID", Int64.Type}, {"Availability", Int64.Type}, {"Demand", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

