table 'Measure Table 2'
	lineageTag: 9881c418-099d-417c-93b4-62d843b7f822

	measure 'Total Loss' = SUMX(FILTER('Demand/Availability Record','Demand/Availability Record'[Loss/Profit]<0),'Demand/Availability Record'[Loss/Profit]*'Demand/Availability Record'[Unit_Price])*-1
		formatString: 0
		lineageTag: 204f0bbd-88fb-4704-8371-dc6598c3c664

	measure 'Total Profit' = SUMX(FILTER('Demand/Availability Record','Demand/Availability Record'[Loss/Profit]>0),'Demand/Availability Record'[Demand])
		formatString: 0
		lineageTag: 200371a9-f46f-4489-82e9-7bbaccab6732

	measure 'Average Loss Per Day' = DIVIDE([Total Loss],[Total Number of Days])
		lineageTag: dafe7b0c-c666-4180-8ffc-e6075f8f441b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Measure Table 2' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

